### PR TITLE
Add None color to colormap

### PR DESCRIPTION
**Pull request by connorjward**
I was getting a `KeyError` when setting the label colour which Trello permits to be `None`. I've extended the `color_map` to account for this (although a `try`, `except` block would also be good here).

### CODE REVIEW

**Comment by maxammann** [comment]
Thanks for the PR!

Should we maybe use the nextcloud blue as the fallback? #0082c9

**Comment by connorjward** [comment]
Ok I've pushed that. I used `"default"` as the key because it's a lot more expressive than `None`. This will affect the other PR though...

I also expanded where you form the `labels` list to make the `try` + `except` more explicit.

**Review by maxammann — CHANGES_REQUESTED** [review]
I think this will cause a merge conflict with your other PR. In this PR you added "default" in the other None.

**Review by maxammann — APPROVED** [review]

**Comment by maxammann** [comment]
Thanks for the contribution!

**Pull request merged**
